name: 'Setup Environment'
description: 'Sets up Python, uv, and caches dependencies'

runs:
  using: "composite"
  steps:
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'

    - name: Set up uv
      uses: astral-sh/setup-uv@v1

    - name: Cache uv global cache
      uses: actions/cache@v4
      with:
        path: ~/.cache/uv
        key: ${{ runner.os }}-uv-${{ hashFiles('**/uv.lock') }}

    - name: Install dependencies
      run: uv pip install -e .[dev]
      shell: bash