# Static list of all available ShopSite pages (from ShopSite admin interface)
SHOPSITE_PAGES = [
    "##FaceBook Store",
    "##FaceBook Store",
    "##orderstatus mod",
    "#BLOG",
    "#Bay State Pet & Garden Supply",
    "#Contact-Thank-You-BSPGS",
    "#Military Discount",
    "#Photos",
    "#Services",
    "#Upcoming-Events-BSPGS",
    "#Video-BSPGS",
    "About: Bay State Pet & Garden Supply",
    "Apparel",
    "Baby Chicks",
    "Barn Supplies Buckets & Feeders",
    "Barn Supplies Farm Gates & Fencing",
    "Barn Supplies Shop All",
    "Barn Supplies Tools & Equipment",
    "Bay State Country Gift Shop",
    "Beekeeping",
    "Black Friday Specials",
    "Boots",
    "Brand - Blue Buffalo",
    "Brand - Blue Seal",
    "Brand - Fromm",
    "Brand - Instinct",
    "Brand - Jonathan Green",
    "Brand - Orijen",
    "Brand - Pro Plan",
    "Brand - Purina",
    "Brand - Science Diet",
    "Brand - Stella & Chewys",
    "Brand - Taste Of The Wild",
    "Brands",
    "Cage Bird Cages & Accessories",
    "Caged Bird Canary & Finch",
    "Caged Bird Cockatiel",
    "Caged Bird Food",
    "Caged Bird Food & Supplies Shop All",
    "Caged Bird Healthcare",
    "Caged Bird Litter & Nesting",
    "Caged Bird Parakeet",
    "Caged Bird Parrot",
    "Caged Bird Pigeon",
    "Caged Bird Toys",
    "Caged Bird Treats",
    "Career Opportunities",
    "Cat Beds & Carriers",
    "Cat Bowls & Feeders",
    "Cat Flea & Tick",
    "Cat Food Dry",
    "Cat Food Raw",
    "Cat Food Shop All",
    "Cat Food Wet",
    "Cat Grooming",
    "Cat Healthcare",
    "Cat Leashes Collars & Harnesses",
    "Cat Litter & Litter Boxes",
    "Cat Supplies Shop All",
    "Cat Toys & Scratchers",
    "Cat Treats",
    "Chick Chat",
    "Chicken Breeds",
    "Contact",
    "Curbside Pick-up",
    "Delivery Services",
    "Dog Beds",
    "Dog Bowls & Feeders",
    "Dog Cleanup",
    "Dog Clothing & Accessories",
    "Dog Crates & Carriers",
    "Dog Dental Treats",
    "Dog Flea & Tick",
    "Dog Food Dry",
    "Dog Food Raw",
    "Dog Food Shop All",
    "Dog Food Wet",
    "Dog Grooming",
    "Dog Healthcare",
    "Dog Leashes Collars & Harnesses",
    "Dog Supplies Shop All",
    "Dog Toys",
    "Dog Treats Biscuits Cookies & Crunchy Treats",
    "Dog Treats Bones Bully Sticks & Natural Chews",
    "Dog Treats Shop All",
    "Dog Treats Soft & Chewy",
    "Employment Opportunities",
    "Example - Brand - Acana",
    "Example - Brand - American Journey",
    "Example - Brand - Frisco",
    "Example - Brand - Hills",
    "Example - Brand - Kong",
    "Example - Brand - NexGard",
    "Example - Brand - Nutro",
    "Example - Brand - Purina",
    "Example - Brand - Royal Canin",
    "Example - Brand - The Disney Collection",
    "Example - Brands",
    "Example Content #1",
    "Example Content #2 Example Content #2 Example Content #2 Example Content #2",
    "Farm Animal Chicken & Poultry",
    "Farm Animal Cow",
    "Farm Animal Llama & Alpaca",
    "Farm Animal Pig",
    "Farm Animal Sheep & Goat",
    "Farm Animal Shop All",
    "Featured Brand - Purina",
    "Featured Products",
    "Fencing & Gates",
    "Fish Food Betta",
    "Fish Food Goldfish",
    "Fish Food Koi & Pond Fish",
    "Fish Food Shop All",
    "Fish Food Tropical",
    "Fish Pond Supplies",
    "Fish Supplies Shop All",
    "Fish Tanks & Accessories",
    "Fish Water Treatments & Test Kits",
    "Flowers & Plants",
    "Food Candy & Refreshments",
    "Gardening Tools & Supplies",
    "Gloves",
    "Grills & Accessories",
    "Hardware",
    "Hay Testing",
    "Heating",
    "Home Shop All",
    "Horse Dewormers",
    "Horse Feed",
    "Horse Feed & Treats Shop All",
    "Horse First Aid",
    "Horse Fly Control",
    "Horse Grooming",
    "Horse Health & Wellness Shop All",
    "Horse Treats",
    "Horse Vitamins & Supplements",
    "Jerky Dog Treats",
    "Kyle - Test",
    "Landscape Professionals",
    "Landscape Services",
    "Lawn & Garden Shop All",
    "Lawn Care",
    "Lawn Care Q&A 2025",
    "Lawn Equipment Rental",
    "Mulch & Loam",
    "Open House",
    "Pest Control",
    "Pest Control & Animal Repellents",
    "Plants",
    "Privacy/Security",
    "Propane Filling Station",
    "Redbarn Canned Dog Food",
    "Reptile Bearded Dragon",
    "Reptile Bedding & Substrate",
    "Reptile Food & Supplies Shop All",
    "Reptile Food & Treats",
    "Reptile Frog",
    "Reptile Heating & Lighting",
    "Reptile Lizard",
    "Reptile Snake",
    "Reptile Tanks & Accessories",
    "Reptile Turtle",
    "Return Merchandise Request Form",
    "Return Request Received",
    "Returns",
    "Search results",
    "Seasonal Products",
    "Seeds & Seed Starting",
    "Shavings & Bedding",
    "Shipping",
    "Shop By Brand",
    "Small Pet Bedding & Litter",
    "Small Pet Food",
    "Small Pet Food & Supplies Shop All",
    "Small Pet Grooming & Health",
    "Small Pet Guinea Pig",
    "Small Pet Habitats & Accessories",
    "Small Pet Hamster",
    "Small Pet Mouse & Rat",
    "Small Pet Rabbit",
    "Small Pet Toys & Chews",
    "Small Pet Treats",
    "Snow Plowing",
    "Soap Lotion & Sanitizer",
    "Soy Candles & Melts",
    "Special Offers",
    "Terms & Conditions",
    "Thank you!",
    "Thank you!",
    "The Christmas Shop",
    "Wild Bird Baths",
    "Wild Bird Feeders",
    "Wild Bird Food Shop All",
    "Wild Bird Hangers Poles & Baffles",
    "Wild Bird Houses",
    "Wild Bird Seed & Seed Mixes",
    "Wild Bird Suet & Mealworms",
    "Wild Bird Supplies Shop All",
    "Wildlife Deer Food",
    "Wildlife Squirrel Food",
    "Winter Supplies",
    "Wood Pellets",
]
