#!/usr/bin/env python3
"""
Post-deployment validation script.
Tests deployed scrapers on platform to ensure they work correctly.
"""

import asyncio
import sys
import argparse
from pathlib import Path
from typing import List, Dict, Any, Optional

# Add project root to path
PROJECT_ROOT = Path(__file__).parent.parent
if str(PROJECT_ROOT) not in sys.path:
    sys.path.insert(0, str(PROJECT_ROOT))

from platform_test_scrapers import test_all_scrapers
from src.core.platform_testing_client import TestingMode


async def validate_deployment(scrapers: Optional[List[str]] = None, verbose: bool = True) -> Dict[str, Any]:
    """
    Validate deployed scrapers on platform.

    Args:
        scrapers: List of specific scrapers to validate (None for all)
        verbose: Enable verbose output

    Returns:
        Dict with validation results
    """
    print("🔍 Starting post-deployment validation...")
    print("Testing deployed scrapers on Apify platform")
    print("=" * 80)

    # Run platform tests
    success = await test_all_scrapers(TestingMode.PLATFORM, verbose)

    if success:
        print("✅ Deployment validation successful!")
        print("All scrapers are working correctly on the platform.")
        return {"success": True, "message": "All tests passed"}
    else:
        print("❌ Deployment validation failed!")
        print("Some scrapers failed platform testing. Check the output above for details.")
        return {"success": False, "message": "Some tests failed"}


async def validate_specific_scraper(scraper_name: str, verbose: bool = True) -> Dict[str, Any]:
    """
    Validate a specific deployed scraper.

    Args:
        scraper_name: Name of the scraper to validate
        verbose: Enable verbose output

    Returns:
        Dict with validation result
    """
    from platform_test_scrapers import test_single_scraper

    print(f"🔍 Validating deployment of {scraper_name}...")

    success = await test_single_scraper(scraper_name, mode=TestingMode.PLATFORM, verbose=verbose)

    if success:
        print(f"✅ {scraper_name} validation successful!")
        return {"success": True, "scraper": scraper_name}
    else:
        print(f"❌ {scraper_name} validation failed!")
        return {"success": False, "scraper": scraper_name}


async def generate_validation_report(results: Dict[str, Any]) -> None:
    """
    Generate a validation report.

    Args:
        results: Validation results
    """
    from datetime import datetime

    report_path = PROJECT_ROOT / "deployment_validation_report.md"

    report = f"""# Deployment Validation Report

**Generated:** {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}

## Summary

- **Status:** {'✅ PASSED' if results['success'] else '❌ FAILED'}
- **Message:** {results['message']}

## Details

This report was generated after deployment to verify that all scrapers
are working correctly on the Apify platform.

### Validation Process

1. **Platform Connection**: Verified API token and connectivity
2. **Actor Availability**: Confirmed all actors are deployed and accessible
3. **Functionality Testing**: Ran test SKUs through each scraper
4. **Data Validation**: Checked output format and data quality
5. **Performance Check**: Verified reasonable execution times

### Next Steps

{'All systems are operational and ready for production use.' if results['success'] else 'Review failed validations and redeploy problematic scrapers.'}

---
*Report generated by deployment validation script*
"""

    with open(report_path, 'w') as f:
        f.write(report)

    print(f"📄 Validation report saved to: {report_path}")


async def main():
    """Main validation function."""
    parser = argparse.ArgumentParser(description="Validate deployed scrapers on Apify platform")
    parser.add_argument("--scraper", help="Validate specific scraper only")
    parser.add_argument("--quiet", action="store_true", help="Suppress verbose output")

    args = parser.parse_args()

    # Validate environment
    from src.core.settings_manager import settings
    if not settings.get("apify_api_token"):
        print("❌ ERROR: Apify API token not configured.")
        print("   Set 'apify_api_token' in settings.json or APIFY_API_TOKEN environment variable")
        return 1

    try:
        if args.scraper:
            result = await validate_specific_scraper(args.scraper, not args.quiet)
            success = result["success"]
        else:
            result = await validate_deployment(verbose=not args.quiet)
            success = result["success"]

        # Generate report
        await generate_validation_report(result)

        return 0 if success else 1

    except Exception as e:
        print(f"❌ Validation failed with error: {e}")
        return 1


if __name__ == "__main__":
    sys.exit(asyncio.run(main()))